export type RootStackParamList = {
  Splash: undefined;
  Login: undefined;
  Otp: { phone: string };
  CompleteProfile: undefined;
  Main: undefined;
  PodDetail: { podId: string };
  Checkout: { podId: string };
  CreatePod: undefined;
  CreateMoment: undefined;
  Notifications: undefined;
  RegisterPlace: undefined;
  Faq: undefined;
  Support: undefined;
  Chatbot: undefined;
  EditProfile: undefined;
  Payments: undefined;
  Privacy: undefined;
  MyPods: undefined;
  Profile: undefined;
  Reviews: { targetType: 'POD' | 'PLACE'; targetId: string; targetTitle: string };
  Feedback: undefined;
  PodIdeas: undefined;
  GoLive: { podId?: string; podTitle?: string } | undefined;
  FollowList: { userId: string; userName: string; initialTab?: 'followers' | 'following' };
  UserProfile: { userId: string };
  YourVenues: undefined;
  Menus: undefined;
  ManageOrders: undefined;
  VenueMoments: undefined;
  Withdrawal: undefined;
};
