import { StyleSheet, Platform, Dimensions } from 'react-native';
import { colors, spacing, borderRadius } from '../../theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
export const MEDIA_MAX_WIDTH = SCREEN_WIDTH * 0.6;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.white },
  header: { fontSize: 28, fontWeight: '700', color: colors.text, paddingHorizontal: spacing.xl, paddingTop: spacing.lg, marginBottom: spacing.lg },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: spacing.xl },
  emptyTitle: { fontSize: 18, fontWeight: '600', color: colors.text, marginBottom: spacing.xs, marginTop: spacing.md },
  emptySubtitle: { fontSize: 14, color: colors.textSecondary, textAlign: 'center' },
  list: { paddingHorizontal: spacing.xl, paddingBottom: 20 },
  chatRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.md, gap: spacing.md },
  avatar: { width: 52, height: 52, borderRadius: 26 },
  chatInfo: { flex: 1 },
  chatName: { fontSize: 16, fontWeight: '600', color: colors.text, marginBottom: 4 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  chatMessage: { fontSize: 14, color: colors.textSecondary },
  separator: { height: 1, backgroundColor: colors.surfaceVariant },
  roomHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.surfaceVariant, gap: spacing.sm },
  backBtn: { padding: spacing.xs },
  roomAvatar: { width: 40, height: 40, borderRadius: 20 },
  roomTitle: { fontSize: 16, fontWeight: '600', color: colors.text },
  roomSubtitle: { fontSize: 12, color: colors.textSecondary },
  messagesList: { padding: spacing.md, paddingBottom: spacing.lg },
  msgRow: { flexDirection: 'row', marginBottom: spacing.sm, alignItems: 'flex-end' },
  msgRowMe: { justifyContent: 'flex-end' },
  msgAvatar: { width: 28, height: 28, borderRadius: 14, marginRight: spacing.xs },
  msgBubble: { maxWidth: '75%', paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: borderRadius.lg },
  msgBubbleOther: { backgroundColor: colors.surfaceVariant },
  msgBubbleMe: { backgroundColor: colors.primary },
  mediaBubble: { paddingHorizontal: spacing.xs, paddingTop: spacing.xs, overflow: 'hidden' },
  msgSenderName: { fontSize: 11, fontWeight: '600', color: colors.primary, marginBottom: 2 },
  msgText: { fontSize: 15, color: colors.text, lineHeight: 20 },
  msgTextMe: { color: colors.white },
  msgTime: { fontSize: 10, color: colors.textTertiary, marginTop: 4, alignSelf: 'flex-end' },
  msgTimeMe: { color: 'rgba(255,255,255,0.7)' },
  mediaThumbnail: { width: MEDIA_MAX_WIDTH, height: MEDIA_MAX_WIDTH * 0.65, borderRadius: borderRadius.md },
  videoThumbWrap: { position: 'relative' as const },
  playOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: 'center' as const, alignItems: 'center' as const },
  uploadingBar: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, gap: spacing.sm, paddingVertical: spacing.xs, backgroundColor: colors.surfaceVariant },
  uploadingText: { fontSize: 13, color: colors.textSecondary },
  inputBar: { flexDirection: 'row', alignItems: 'flex-end', paddingHorizontal: spacing.sm, paddingVertical: spacing.sm, borderTopWidth: 1, borderTopColor: colors.surfaceVariant, backgroundColor: colors.white, gap: spacing.xs },
  attachBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.surfaceVariant, justifyContent: 'center', alignItems: 'center' },
  input: { flex: 1, backgroundColor: colors.surfaceVariant, borderRadius: borderRadius.lg, paddingHorizontal: spacing.md, paddingVertical: Platform.OS === 'ios' ? spacing.sm : spacing.xs, fontSize: 15, maxHeight: 100, color: colors.text },
  sendBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.primary, justifyContent: 'center', alignItems: 'center' },
  sendBtnDisabled: { opacity: 0.4 },
  attachRow: { flexDirection: 'row' as const, paddingHorizontal: spacing.xl, paddingVertical: spacing.md, gap: spacing.xl, borderTopWidth: 1, borderTopColor: colors.surfaceVariant, backgroundColor: colors.white },
  attachOption: { alignItems: 'center' as const, gap: spacing.xs },
  attachCircle: { width: 50, height: 50, borderRadius: 25, justifyContent: 'center' as const, alignItems: 'center' as const },
  attachLabel: { fontSize: 12, color: colors.textSecondary, fontWeight: '500' as const },
});

export const pvStyles = StyleSheet.create({
  backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.92)', justifyContent: 'center', alignItems: 'center' },
  closeBtn: { position: 'absolute', top: 50, right: 20, zIndex: 10, padding: 8 },
  fullImage: { width: '100%', height: '80%' },
});
