import { StyleSheet } from 'react-native';
import { colors, spacing, borderRadius } from '../../theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.white },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.xl, paddingVertical: spacing.md },
  headerBtn: { width: 36, height: 36, justifyContent: 'center', alignItems: 'center' },
  headerTitle: { fontSize: 18, fontWeight: '700', color: colors.text },
  stepIndicator: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.xxl, paddingBottom: spacing.lg },
  stepItem: { flexDirection: 'row', alignItems: 'center' },
  stepCircle: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.surfaceVariant, justifyContent: 'center', alignItems: 'center' },
  stepCircleActive: { backgroundColor: colors.primary },
  stepNum: { fontSize: 12, fontWeight: '600', color: colors.textTertiary },
  stepNumActive: { color: colors.white },
  stepLabel: { fontSize: 11, color: colors.textTertiary, marginLeft: 4, fontWeight: '500' },
  stepLabelActive: { color: colors.primary },
  stepLine: { width: 24, height: 2, backgroundColor: colors.surfaceVariant, marginHorizontal: 6 },
  stepLineActive: { backgroundColor: colors.primary },
  scrollContent: { flex: 1, paddingHorizontal: spacing.xl },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: colors.text, marginTop: spacing.lg, marginBottom: spacing.md },
  helperText: { fontSize: 14, color: colors.textSecondary, lineHeight: 22, marginBottom: spacing.lg },
  fieldContainer: { marginBottom: spacing.lg },
  fieldLabel: { fontSize: 13, fontWeight: '600', color: colors.textSecondary, marginBottom: spacing.xs },
  inputRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: borderRadius.sm, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.border },
  inputRowError: { borderColor: colors.error },
  input: { flex: 1, fontSize: 15, color: colors.text, paddingVertical: 12 },
  inputMultiline: { minHeight: 60, textAlignVertical: 'top' },
  errorText: { fontSize: 12, color: colors.error, marginTop: 4 },
  categoryContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.sm },
  categoryBtn: { paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, borderRadius: borderRadius.full, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  categoryBtnActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  categoryBtnText: { fontSize: 13, fontWeight: '500', color: colors.textSecondary },
  categoryBtnTextActive: { color: colors.white },
  uploadBox: { alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: colors.border, borderStyle: 'dashed', borderRadius: borderRadius.md, paddingVertical: spacing.xxl, marginBottom: spacing.lg, overflow: 'hidden' },
  uploadPreviewImg: { width: '100%', height: 120, resizeMode: 'cover' } as const,
  photosRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, padding: spacing.sm },
  photoThumb: { width: 60, height: 60, borderRadius: borderRadius.sm },
  uploadingRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, justifyContent: 'center', marginVertical: spacing.md },
  uploadingText: { fontSize: 13, color: colors.primary, fontWeight: '500' },
  uploadTitle: { fontSize: 15, fontWeight: '600', color: colors.text, marginTop: spacing.sm },
  uploadSubtext: { fontSize: 13, color: colors.textTertiary, marginTop: 2 },
  policyCard: { backgroundColor: colors.surface, borderRadius: borderRadius.md, padding: spacing.lg, marginBottom: spacing.md },
  policyHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.sm },
  policyTitle: { fontSize: 15, fontWeight: '600', color: colors.text, flex: 1 },
  policyContent: { fontSize: 14, color: colors.textSecondary, lineHeight: 22 },
  emptyPolicies: { alignItems: 'center', paddingVertical: spacing.xxxl },
  emptyPoliciesText: { fontSize: 14, color: colors.textTertiary, marginTop: spacing.md },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', marginTop: spacing.lg, gap: spacing.md },
  checkbox: { width: 24, height: 24, borderRadius: 6, borderWidth: 2, borderColor: colors.border, justifyContent: 'center', alignItems: 'center' },
  checkboxActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  checkboxLabel: { fontSize: 14, color: colors.text, flex: 1 },
  checkboxDisabled: { color: colors.textTertiary },
  scrollHint: { fontSize: 12, color: colors.textTertiary, marginTop: spacing.xs, marginLeft: 36 },
  btnContainer: { paddingVertical: spacing.xxl },
});

export default styles;
