import { StyleSheet } from 'react-native';

import { ThemeUtils } from '../../hooks/useThemedStyles';

export const createStyles = ({ colors, spacing, borderRadius }: ThemeUtils) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.white },
    centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    profileHeader: { alignItems: 'center', paddingTop: spacing.xxl, paddingBottom: spacing.xl },
    avatarGradient: {
      width: 88,
      height: 88,
      borderRadius: 44,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: spacing.md,
    },
    avatar: { width: 80, height: 80, borderRadius: 40, borderWidth: 3, borderColor: colors.white },
    userName: { fontSize: 22, fontWeight: '700', color: colors.text },
    userPhone: { fontSize: 14, color: colors.textSecondary, marginTop: 2 },
    verifiedBadge: {
      marginTop: spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
      backgroundColor: colors.success + '20',
      borderRadius: borderRadius.full,
    },
    verifiedBadgeText: { fontSize: 12, fontWeight: '600', color: colors.success },
    statsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: spacing.xl,
      paddingHorizontal: spacing.xxxl,
    },
    statItem: { flex: 1, alignItems: 'center' },
    statValue: { fontSize: 20, fontWeight: '700', color: colors.text },
    statLabel: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
    statDivider: { width: 1, height: 32, backgroundColor: colors.border },
    menuContainer: { paddingHorizontal: spacing.xl, marginTop: spacing.md },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.surfaceVariant,
      gap: spacing.md,
    },
    menuContent: { flex: 1 },
    menuLabel: { fontSize: 16, fontWeight: '600', color: colors.text },
    menuSubtitle: { fontSize: 13, color: colors.textSecondary, marginTop: 1 },
    logoutButton: {
      marginHorizontal: spacing.xl,
      marginTop: spacing.xxl,
      paddingVertical: spacing.lg,
      borderRadius: borderRadius.md,
      borderWidth: 1.5,
      borderColor: colors.error,
      alignItems: 'center',
    },
    logoutText: { fontSize: 16, fontWeight: '600', color: colors.error },
    version: {
      textAlign: 'center',
      fontSize: 12,
      color: colors.textTertiary,
      marginTop: spacing.lg,
      marginBottom: spacing.xxxl,
    },
  });
