import { StyleSheet } from 'react-native';

import { ThemeUtils } from '../../hooks/useThemedStyles';

export const createStyles = ({ colors, spacing, borderRadius }: ThemeUtils) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.surface },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.surfaceVariant,
      gap: spacing.md,
    },
    headerTitle: { fontSize: 18, fontWeight: '700', color: colors.text },
    scrollContent: { padding: spacing.lg, paddingBottom: 120, flexGrow: 1 },
    podCard: {
      flexDirection: 'row',
      backgroundColor: colors.surface,
      borderRadius: borderRadius.lg,
      overflow: 'hidden',
      marginBottom: spacing.lg,
    },
    podImage: { width: 100, height: 100 },
    podImagePlaceholder: {
      width: 100,
      height: 100,
      backgroundColor: colors.surfaceVariant,
      justifyContent: 'center',
      alignItems: 'center',
    },
    podInfo: { flex: 1, padding: spacing.md, justifyContent: 'center' },
    podTitle: { fontSize: 16, fontWeight: '700', color: colors.text, marginBottom: 4 },
    podMeta: { fontSize: 13, color: colors.textSecondary, marginBottom: 2 },
    section: { marginBottom: spacing.lg },
    sectionTitle: { fontSize: 16, fontWeight: '700', color: colors.text, marginBottom: spacing.sm },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: spacing.sm,
    },
    rowLabel: { fontSize: 14, color: colors.textSecondary },
    rowValue: { fontSize: 14, fontWeight: '600', color: colors.text },
    divider: { height: 1, backgroundColor: colors.surfaceVariant, marginVertical: spacing.sm },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: spacing.md,
    },
    totalLabel: { fontSize: 16, fontWeight: '700', color: colors.text },
    totalValue: { fontSize: 20, fontWeight: '800', color: colors.primary },
    dummyBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: colors.warningBg,
      borderRadius: borderRadius.md,
      padding: spacing.md,
      marginBottom: spacing.lg,
    },
    dummyText: { flex: 1, fontSize: 13, color: colors.warningText, lineHeight: 18 },
    subscriptionBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: `${colors.primary}15`,
      borderRadius: borderRadius.md,
      padding: spacing.md,
      marginBottom: spacing.lg,
    },
    subscriptionText: { flex: 1, fontSize: 13, color: colors.primary, lineHeight: 18 },
    bottomBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.surface,
      borderTopWidth: 1,
      borderTopColor: colors.surfaceVariant,
      paddingHorizontal: spacing.lg,
      paddingTop: spacing.md,
    },
    payBtn: {
      backgroundColor: colors.primary,
      borderRadius: borderRadius.full,
      paddingVertical: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: spacing.sm,
    },
    payBtnDisabled: { opacity: 0.5 },
    payBtnText: { fontSize: 16, fontWeight: '700', color: colors.white },
    successContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: spacing.xl,
    },
    successTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: colors.text,
      marginTop: spacing.lg,
      marginBottom: spacing.sm,
    },
    successSubtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
    },
    successBtn: {
      backgroundColor: colors.primary,
      borderRadius: borderRadius.full,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.xl * 2,
      marginTop: spacing.xl,
    },
    successBtnText: { fontSize: 16, fontWeight: '700', color: colors.white },
  });
