import { StyleSheet } from 'react-native';
import { ThemeUtils } from '../../hooks/useThemedStyles';

const createStyles = ({ colors, spacing, borderRadius }: ThemeUtils) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.surface },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.xl,
      paddingVertical: spacing.md,
    },
    headerBtn: { width: 36, height: 36, justifyContent: 'center', alignItems: 'center' },
    headerTitle: { fontSize: 18, fontWeight: '700', color: colors.text },
    stepIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.xxl,
      paddingBottom: spacing.lg,
    },
    stepItem: { flexDirection: 'row', alignItems: 'center' },
    stepCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.surfaceVariant,
      justifyContent: 'center',
      alignItems: 'center',
    },
    stepCircleActive: { backgroundColor: colors.primary },
    stepNum: { fontSize: 12, fontWeight: '600', color: colors.textTertiary },
    stepNumActive: { color: colors.white },
    stepLabel: { fontSize: 11, color: colors.textTertiary, marginLeft: 4, fontWeight: '500' },
    stepLabelActive: { color: colors.primary },
    stepLine: {
      width: 24,
      height: 2,
      backgroundColor: colors.surfaceVariant,
      marginHorizontal: 6,
    },
    stepLineActive: { backgroundColor: colors.primary },
    scrollContent: { paddingHorizontal: spacing.xl, paddingBottom: spacing.xxxl },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      marginTop: spacing.lg,
      marginBottom: spacing.md,
    },
    helperText: {
      fontSize: 14,
      color: colors.textSecondary,
      lineHeight: 22,
      marginBottom: spacing.lg,
    },
    fieldContainer: { marginBottom: spacing.lg },
    fieldLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: spacing.xs,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: borderRadius.sm,
      paddingHorizontal: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
    },
    inputRowError: { borderColor: colors.error },
    input: { flex: 1, fontSize: 15, color: colors.text, paddingVertical: 12 },
    errorText: { fontSize: 12, color: colors.error, marginTop: 4 },
    checkboxRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: spacing.sm,
      gap: spacing.sm,
    },
    checkbox: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    checkboxActive: { backgroundColor: colors.primary, borderColor: colors.primary },
    checkboxLabel: { fontSize: 13, color: colors.textSecondary, flex: 1 },
    verifyBtn: {
      backgroundColor: colors.primary,
      borderRadius: borderRadius.sm,
      paddingVertical: 12,
      alignItems: 'center',
      marginTop: spacing.md,
    },
    verifyBtnDisabled: { opacity: 0.5 },
    verifyBtnText: { color: colors.white, fontSize: 15, fontWeight: '600' },
    otpRow: {
      flexDirection: 'row',
      gap: spacing.sm,
      marginTop: spacing.md,
    },
    otpInput: {
      flex: 1,
      fontSize: 15,
      color: colors.text,
      paddingVertical: 12,
      paddingHorizontal: spacing.md,
      borderRadius: borderRadius.sm,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    verifiedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      backgroundColor: '#E8F5E9',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: borderRadius.sm,
      marginTop: spacing.sm,
    },
    verifiedText: { fontSize: 13, color: '#2E7D32', fontWeight: '500' },
    /* Calendar */
    calendarContainer: { marginBottom: spacing.lg },
    calendarHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: spacing.lg,
    },
    calendarMonthText: { fontSize: 16, fontWeight: '700', color: colors.text },
    calendarNavBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.surfaceVariant,
      justifyContent: 'center',
      alignItems: 'center',
    },
    calendarWeekRow: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: spacing.sm,
    },
    calendarWeekDay: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textTertiary,
      width: 40,
      textAlign: 'center',
    },
    calendarGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    calendarDayCell: {
      width: '14.28%',
      alignItems: 'center',
      paddingVertical: spacing.sm,
    },
    calendarDay: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
    },
    calendarDaySelected: { backgroundColor: colors.primary },
    calendarDayToday: { borderWidth: 1, borderColor: colors.primary },
    calendarDayDisabled: { opacity: 0.3 },
    calendarDayText: { fontSize: 14, color: colors.text, fontWeight: '500' },
    calendarDayTextSelected: { color: colors.white },
    calendarDayTextDisabled: { color: colors.textTertiary },
    selectedDateText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.primary,
      textAlign: 'center',
      marginBottom: spacing.lg,
    },
    /* Time Slots */
    timeSlotsTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
      marginBottom: spacing.md,
    },
    timeSlotsContainer: { gap: spacing.sm },
    timeSlot: {
      paddingVertical: 14,
      paddingHorizontal: spacing.lg,
      borderRadius: borderRadius.sm,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    timeSlotSelected: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    timeSlotDisabled: { opacity: 0.4, backgroundColor: colors.surfaceVariant },
    timeSlotText: { fontSize: 14, fontWeight: '500', color: colors.text, textAlign: 'center' },
    timeSlotTextSelected: { color: colors.white },
    timeSlotTextDisabled: { color: colors.textTertiary },
    /* Buttons */
    btnContainer: { paddingVertical: spacing.xxl, paddingHorizontal: spacing.xl },
    submitBtn: {
      backgroundColor: colors.primary,
      borderRadius: borderRadius.sm,
      paddingVertical: 16,
      alignItems: 'center',
    },
    submitBtnDisabled: { opacity: 0.5 },
    submitBtnText: { color: colors.white, fontSize: 16, fontWeight: '700' },
    /* Success */
    successContainer: { alignItems: 'center', paddingVertical: spacing.xxxxl },
    successIcon: { marginBottom: spacing.xl },
    successTitle: { fontSize: 22, fontWeight: '700', color: colors.text, marginBottom: spacing.md },
    successSubtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 22,
      paddingHorizontal: spacing.xl,
    },
  });

export { createStyles };
