import { StyleSheet } from 'react-native';

import { ThemeUtils } from '../../hooks/useThemedStyles';

const createStyles = ({ colors, spacing, borderRadius }: ThemeUtils) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.white },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: spacing.xl, paddingVertical: spacing.md },
  headerTitle: { fontSize: 16, fontWeight: '600', color: colors.text },
  scrollView: { flex: 1, paddingHorizontal: spacing.xl },
  title: { fontSize: 28, fontWeight: '700', color: colors.text, marginBottom: spacing.xs },
  subtitle: { fontSize: 15, color: colors.textSecondary, marginBottom: spacing.xxl },
  inputLabel: { fontSize: 12, fontWeight: '600', color: colors.text, letterSpacing: 1, marginBottom: spacing.sm, marginTop: spacing.lg },
  textInput: { borderWidth: 1, borderColor: colors.border, borderRadius: borderRadius.md, padding: spacing.lg, fontSize: 16, color: colors.text, backgroundColor: colors.white },
  textArea: { minHeight: 100 },
  inputError: { borderColor: colors.error },
  errorText: { fontSize: 12, color: colors.error, marginTop: spacing.xs, marginLeft: spacing.xs },
  categoryRow: { flexDirection: 'row', gap: spacing.sm, flexWrap: 'wrap' },
  categoryChip: { paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, borderRadius: borderRadius.full, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  categoryChipActive: { borderColor: colors.primary, backgroundColor: colors.primary + '15' },
  categoryChipText: { fontSize: 14, color: colors.textSecondary, fontWeight: '500' },
  categoryChipTextActive: { color: colors.primary, fontWeight: '600' },
  sectionTitle: { fontSize: 20, fontWeight: '700', color: colors.text, marginTop: spacing.xxl, marginBottom: spacing.sm },
  logisticsRow: { flexDirection: 'row', gap: spacing.lg },
  logisticsItem: { flex: 1 },
  feeInput: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: borderRadius.md, paddingHorizontal: spacing.lg, paddingVertical: spacing.md },
  currencySymbol: { fontSize: 16, color: colors.textSecondary, marginRight: spacing.xs },
  feeTextInput: { flex: 1, fontSize: 16, fontWeight: '600', color: colors.text },
  counterRow: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: borderRadius.md, overflow: 'hidden' },
  counterButton: { paddingHorizontal: spacing.lg, paddingVertical: spacing.md, backgroundColor: colors.surface },
  counterButtonText: { fontSize: 18, color: colors.textSecondary },
  counterValue: { flex: 1, textAlign: 'center', fontSize: 16, fontWeight: '600', color: colors.text },
  datePickerRow: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: borderRadius.md, padding: spacing.lg, gap: spacing.md, backgroundColor: colors.surface },
  dateText: { flex: 1, fontSize: 15, color: colors.text, fontWeight: '500' },
  bottom: { paddingHorizontal: spacing.xl, paddingBottom: spacing.xxl, paddingTop: spacing.md },
  mediaRow: { flexDirection: 'row', gap: spacing.md },
  uploadBox: { flex: 1, height: 120, borderWidth: 2, borderStyle: 'dashed', borderColor: colors.border, borderRadius: borderRadius.md, justifyContent: 'center', alignItems: 'center', overflow: 'hidden', backgroundColor: colors.surface },
  uploadPreview: { width: '100%', height: '100%', resizeMode: 'cover' } as const,
  uploadingCenter: { justifyContent: 'center', alignItems: 'center', gap: spacing.xs },
  uploadProgressText: { fontSize: 12, color: colors.primary, fontWeight: '600' as const },
  uploadLabel: { fontSize: 13, color: colors.textSecondary, marginTop: spacing.xs, fontWeight: '500' as const },
  payoutCardWrap: { backgroundColor: colors.surface, borderRadius: borderRadius.lg, padding: spacing.xl, marginTop: spacing.xxl, marginBottom: spacing.xxxl },
  payoutHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.lg },
  payoutTitle: { fontSize: 16, fontWeight: '700' as const, color: colors.text },
  payoutRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.sm },
  payoutLabel: { fontSize: 14, color: colors.textSecondary },
  payoutValue: { fontSize: 14, color: colors.text },
  verifiedRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: spacing.xs, marginTop: spacing.md },
  verifiedText: { fontSize: 13, color: colors.textSecondary },
});

export { createStyles };
