import { StyleSheet } from 'react-native';

import { ThemeUtils } from '../../hooks/useThemedStyles';

export const createStyles = ({ colors, spacing, borderRadius }: ThemeUtils) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.surface },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.surfaceVariant,
      backgroundColor: colors.surface,
      gap: spacing.sm,
    },
    headerTitle: { fontSize: 18, fontWeight: '700', color: colors.text, flex: 1 },
    content: { padding: spacing.md, paddingBottom: 100 },

    /* Live session card */
    sessionCard: {
      backgroundColor: colors.surface,
      borderRadius: borderRadius.md,
      overflow: 'hidden',
      marginBottom: spacing.md,
    },
    liveBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
      backgroundColor: colors.error,
    },
    liveTag: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    liveDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.surface,
    },
    liveText: { fontSize: 12, fontWeight: '700', color: colors.white },
    viewerCount: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    viewerText: { fontSize: 12, color: colors.white, fontWeight: '600' },
    sessionBody: { padding: spacing.md },
    sessionHostRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    hostAvatar: { width: 40, height: 40, borderRadius: 20 },
    hostAvatarPlaceholder: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.primaryLight,
      justifyContent: 'center',
      alignItems: 'center',
    },
    hostName: { fontSize: 14, fontWeight: '600', color: colors.text },
    podName: { fontSize: 12, color: colors.textSecondary },
    sessionTitle: { fontSize: 16, fontWeight: '700', color: colors.text, marginBottom: 4 },
    sessionDesc: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
      marginBottom: spacing.md,
    },
    joinBtn: {
      backgroundColor: colors.primary,
      borderRadius: borderRadius.md,
      paddingVertical: spacing.sm,
      alignItems: 'center',
    },
    joinBtnText: { color: colors.white, fontSize: 14, fontWeight: '600' },
    leaveBtn: {
      backgroundColor: colors.surfaceVariant,
      borderRadius: borderRadius.md,
      paddingVertical: spacing.sm,
      alignItems: 'center',
    },
    leaveBtnText: { color: colors.error, fontSize: 14, fontWeight: '600' },
    startedAt: {
      fontSize: 11,
      color: colors.textTertiary,
      marginTop: spacing.sm,
      textAlign: 'right',
    },

    /* FAB */
    fab: {
      position: 'absolute',
      bottom: 24,
      right: 24,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.error,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 6,
      shadowColor: colors.error,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },

    /* Modal */
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: borderRadius.lg,
      borderTopRightRadius: borderRadius.lg,
      padding: spacing.lg,
      paddingBottom: spacing.xxxl,
    },
    modalTitle: { fontSize: 18, fontWeight: '700', color: colors.text, marginBottom: spacing.md },
    input: {
      backgroundColor: colors.surfaceVariant,
      borderRadius: borderRadius.md,
      padding: spacing.md,
      fontSize: 14,
      color: colors.text,
      marginBottom: spacing.md,
    },
    textArea: { minHeight: 80, textAlignVertical: 'top' },
    inputError: { borderWidth: 1, borderColor: colors.error },
    errorText: {
      fontSize: 12,
      color: colors.error,
      marginTop: -spacing.sm,
      marginBottom: spacing.sm,
      marginLeft: spacing.xs,
    },
    submitBtn: {
      backgroundColor: colors.error,
      borderRadius: borderRadius.md,
      paddingVertical: spacing.md,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      gap: spacing.sm,
      marginTop: spacing.xs,
    },
    submitBtnText: { color: colors.white, fontSize: 16, fontWeight: '700' },
    submitBtnDisabled: { opacity: 0.5 },

    centered: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: spacing.xl,
    },
    emptyText: { fontSize: 16, fontWeight: '600', color: colors.text, marginTop: spacing.md },
    emptySubtext: {
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: spacing.xs,
      textAlign: 'center',
    },
  });
