import { StyleSheet, Dimensions } from 'react-native';
import { ThemeUtils } from '../../hooks/useThemedStyles';

const { width } = Dimensions.get('window');

const createStyles = ({ colors, spacing, borderRadius }: ThemeUtils) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.white },
  scrollView: { flex: 1 },
  heroContainer: { height: 280, position: 'relative' },
  heroImage: { width: '100%', height: '100%' },
  heroOverlay: { position: 'absolute', top: 0, left: 0, right: 0, flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: spacing.lg, paddingTop: spacing.sm },
  iconButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0,0,0,0.3)', justifyContent: 'center', alignItems: 'center' },
  statusContainer: { position: 'absolute', bottom: 0, left: 0 },
  statusBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primary, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, borderTopRightRadius: borderRadius.sm, gap: spacing.xs },
  statusText: { color: colors.white, fontSize: 12, fontWeight: '700', letterSpacing: 0.5 },
  content: { padding: spacing.xl },
  title: { fontSize: 28, fontWeight: '700', color: colors.text, marginBottom: spacing.lg, lineHeight: 34 },
  hostRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: spacing.xxl },
  hostInfo: {},
  hostedBy: { fontSize: 10, fontWeight: '600', color: colors.textSecondary, letterSpacing: 1, marginBottom: 4 },
  hostNameRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  hostAvatar: { width: 32, height: 32, borderRadius: 16 },
  hostName: { fontSize: 16, fontWeight: '600', color: colors.text },
  ratingContainer: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  ratingScore: { fontSize: 16, fontWeight: '700', color: colors.text },
  reviewCount: { fontSize: 14, color: colors.textSecondary },
  infoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginBottom: spacing.xxl },
  infoCard: { width: (width - spacing.xl * 2 - spacing.md) / 2, padding: spacing.lg, borderRadius: borderRadius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white },
  infoLabel: { fontSize: 12, color: colors.textSecondary, marginBottom: 2, marginTop: spacing.sm },
  infoValue: { fontSize: 15, fontWeight: '700', color: colors.text },
  infoSubValue: { fontSize: 12, color: colors.textSecondary, marginTop: 1 },
  attendeesSection: { marginBottom: spacing.xxl },
  attendeesHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.md },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: colors.text },
  viewAll: { fontSize: 14, fontWeight: '600', color: colors.primary },
  attendeesRow: { flexDirection: 'row', alignItems: 'center' },
  attendeeAvatar: { width: 36, height: 36, borderRadius: 18, borderWidth: 2, borderColor: colors.white },
  moreAttendees: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.surfaceVariant, justifyContent: 'center', alignItems: 'center', marginLeft: -10 },
  moreAttendeesText: { fontSize: 11, fontWeight: '600', color: colors.textSecondary },
  joiningText: { fontSize: 13, color: colors.textSecondary, marginLeft: spacing.md },
  planSection: { marginBottom: spacing.xxl },
  planText: { fontSize: 15, color: colors.textSecondary, lineHeight: 24, marginTop: spacing.md },
  trustNote: { flexDirection: 'row', backgroundColor: '#EFF6FF', padding: spacing.lg, borderRadius: borderRadius.md, gap: spacing.sm, marginBottom: spacing.xxxl },
  trustText: { flex: 1, fontSize: 13, color: colors.textSecondary, lineHeight: 20 },
  trustBold: { fontWeight: '700', color: colors.text },
  bottomBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: spacing.xl, paddingVertical: spacing.lg, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.white },
  priceInfo: {},
  totalLabel: { fontSize: 12, color: colors.textSecondary },
  totalPrice: { fontSize: 22, fontWeight: '700', color: colors.text },
  perPerson: { fontSize: 12, color: colors.textSecondary },
  joinButton: { borderRadius: borderRadius.md, overflow: 'hidden' },
  joinGradient: { paddingHorizontal: spacing.xxl, paddingVertical: spacing.lg, borderRadius: borderRadius.md },
  joinText: { color: colors.white, fontSize: 16, fontWeight: '700' },
});

export { createStyles };
