import { StyleSheet } from 'react-native';
import { ThemeUtils } from '../../../hooks/useThemedStyles';

export const createStyles = ({ colors, spacing, borderRadius }: ThemeUtils) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.surface },
    content: { flex: 1, paddingHorizontal: spacing.xl },
    topSection: { paddingTop: 60, flex: 1 },
    logoBox: {
      width: 56,
      height: 56,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: spacing.xxl,
    },
    title: {
      fontSize: 32,
      fontWeight: '700',
      color: colors.text,
      marginBottom: spacing.sm,
      letterSpacing: -0.5,
    },
    subtitle: {
      fontSize: 16,
      color: colors.textSecondary,
      lineHeight: 24,
      marginBottom: spacing.xxxl,
    },
    inputLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.text,
      letterSpacing: 1,
      marginBottom: spacing.sm,
    },
    phoneInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: borderRadius.md,
      overflow: 'hidden',
      marginBottom: spacing.sm,
    },
    countryCodeBox: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.lg,
      borderRightWidth: 1,
      borderRightColor: colors.border,
      backgroundColor: colors.surface,
    },
    countryCodeText: { fontSize: 16, fontWeight: '500', color: colors.text },
    phoneInput: {
      flex: 1,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.lg,
      fontSize: 16,
      color: colors.text,
    },
    errorText: {
      fontSize: 12,
      color: colors.error,
      marginBottom: spacing.sm,
      marginLeft: spacing.xs,
    },
    secureBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      marginTop: spacing.sm,
    },
    secureText: { fontSize: 14, color: colors.success, fontWeight: '500' },
    bottomSection: { marginTop: 'auto', paddingBottom: 40, paddingTop: spacing.xxxl },
    termsText: {
      textAlign: 'center',
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: spacing.lg,
      lineHeight: 20,
    },
    termsLink: { color: colors.primary, fontWeight: '600' },
    policyLinksRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: spacing.sm,
      gap: spacing.sm,
    },
    policyLinkSmall: { fontSize: 12, color: colors.primary, fontWeight: '600' },
    policyDot: { fontSize: 12, color: colors.textTertiary },
    modalOverlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' },
    modalContainer: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: '85%',
      minHeight: '50%',
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.xl,
      paddingVertical: spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: colors.surfaceVariant,
    },
    modalTitle: { fontSize: 18, fontWeight: '700', color: colors.text },
    modalCloseBtn: { padding: spacing.xs },
    modalScroll: { flex: 1 },
    modalScrollContent: {
      paddingHorizontal: spacing.xl,
      paddingVertical: spacing.lg,
      paddingBottom: 40,
    },
    modalLoading: { paddingVertical: spacing.xxxl, alignItems: 'center', gap: spacing.sm },
    modalLoadingText: { fontSize: 14, color: colors.textSecondary },
    policyCard: {
      backgroundColor: colors.surface,
      borderRadius: borderRadius.md,
      padding: spacing.lg,
      marginBottom: spacing.md,
      borderWidth: 1,
      borderColor: colors.surfaceVariant,
    },
    policyCardTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      marginBottom: spacing.sm,
    },
    policyCardContent: { fontSize: 14, color: colors.textSecondary, lineHeight: 22 },
  });
