import { StyleSheet, Platform } from 'react-native';

import { ThemeUtils } from '../../hooks/useThemedStyles';

export const createStyles = ({ colors, spacing, borderRadius }: ThemeUtils) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.surface },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.surfaceVariant,
      backgroundColor: colors.surface,
      gap: spacing.sm,
    },
    headerTitle: { fontSize: 18, fontWeight: '700', color: colors.text, flex: 1 },
    content: { padding: spacing.md, paddingBottom: 100 },

    /* Idea card */
    ideaCard: {
      backgroundColor: colors.surface,
      borderRadius: borderRadius.md,
      padding: spacing.md,
      marginBottom: spacing.md,
    },
    ideaHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    ideaAvatar: { width: 32, height: 32, borderRadius: 16 },
    ideaAvatarPlaceholder: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.primaryLight,
      justifyContent: 'center',
      alignItems: 'center',
    },
    ideaUserName: { fontSize: 13, fontWeight: '600', color: colors.text, flex: 1 },
    ideaStatus: {
      paddingHorizontal: spacing.sm,
      paddingVertical: 2,
      borderRadius: borderRadius.full,
    },
    statusPending: { backgroundColor: colors.warning + '20' },
    statusApproved: { backgroundColor: colors.success + '20' },
    statusRejected: { backgroundColor: colors.error + '20' },
    statusText: { fontSize: 10, fontWeight: '700' },
    statusPendingText: { color: colors.warning },
    statusApprovedText: { color: colors.success },
    statusRejectedText: { color: colors.error },
    ideaTitle: { fontSize: 16, fontWeight: '700', color: colors.text, marginBottom: spacing.xs },
    ideaDesc: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
      marginBottom: spacing.sm,
    },
    metaRow: { flexDirection: 'row', gap: spacing.lg, marginBottom: spacing.sm },
    metaItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    metaText: { fontSize: 12, color: colors.textSecondary },
    ideaFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: spacing.sm,
      borderTopWidth: 1,
      borderTopColor: colors.surfaceVariant,
    },
    upvoteBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: spacing.xs,
      paddingHorizontal: spacing.md,
      borderRadius: borderRadius.full,
      backgroundColor: colors.surfaceVariant,
    },
    upvoteBtnActive: {
      backgroundColor: colors.primary + '15',
    },
    upvoteText: { fontSize: 14, fontWeight: '600', color: colors.textSecondary },
    upvoteTextActive: { color: colors.primary },
    ideaDate: { fontSize: 11, color: colors.textTertiary },

    /* FAB + Modal */
    fab: {
      position: 'absolute',
      bottom: Platform.OS === 'android' ? 40 : 24,
      right: 24,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 6,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: borderRadius.lg,
      borderTopRightRadius: borderRadius.lg,
      padding: spacing.lg,
      paddingBottom: spacing.xxxl,
    },
    modalTitle: { fontSize: 18, fontWeight: '700', color: colors.text, marginBottom: spacing.md },
    input: {
      backgroundColor: colors.surfaceVariant,
      borderRadius: borderRadius.md,
      padding: spacing.md,
      fontSize: 14,
      color: colors.text,
      marginBottom: spacing.md,
    },
    textArea: { minHeight: 100, textAlignVertical: 'top' },
    inputError: { borderWidth: 1, borderColor: colors.error },
    errorText: {
      fontSize: 12,
      color: colors.error,
      marginTop: -spacing.sm,
      marginBottom: spacing.sm,
      marginLeft: spacing.xs,
    },
    rowInputs: { flexDirection: 'row', gap: spacing.sm },
    halfInput: { flex: 1 },
    submitBtn: {
      backgroundColor: colors.primary,
      borderRadius: borderRadius.md,
      paddingVertical: spacing.md,
      alignItems: 'center',
      marginTop: spacing.xs,
    },
    submitBtnText: { color: colors.white, fontSize: 16, fontWeight: '600' },
    submitBtnDisabled: { opacity: 0.5 },

    centered: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: spacing.xl,
    },
    emptyText: { fontSize: 16, fontWeight: '600', color: colors.text, marginTop: spacing.md },
    emptySubtext: {
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: spacing.xs,
      textAlign: 'center',
    },
  });
